In [2]:
#import cmath

import cmath


In [20]:
cmath.sqrt(4)


(2+0j)

In [22]:
cmath.sqrt(16)

(4+0j)

In [24]:
cmath.sqrt(-1)

1j

In [26]:
cmath.exp(4)

(54.598150033144236+0j)

In [28]:
cmath.exp(1)

(2.718281828459045+0j)

In [30]:
cmath.log(2)

(0.6931471805599453+0j)

In [32]:
cmath.log(4)

(1.3862943611198906+0j)

In [34]:
cmath.sin(60)

(-0.3048106211022167-0j)

In [62]:
#import numpy as np
import numpy as np

# Addition
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.add(x, y))  # [5, 7, 9]

# Subtraction
print(np.subtract(x, y))  # [-3, -3, -3]

# Multiplication
print(np.multiply(x, y))  # [ 4, 10, 18]

# Division
print(np.divide(x, y))  # [0.25, 0.4 , 0.5 ]

# Power
print(np.power(x, 2))  # [1, 4, 9]

# Modulo
print(np.remainder(x, y))  # [1, 2, 3]

# Square root
print(np.sqrt(x))  # [1. 1.41421356 1.73205081]

# Absolute value
print(np.abs(x))  # [1 2 3]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1 2 3]
[1.         1.41421356 1.73205081]
[1 2 3]


In [64]:
print(np.remainder(x, y))

[1 2 3]


In [66]:
# Sine, Cosine, Tangent
angle = np.array([0, np.pi/2, np.pi])
print(np.sin(angle))  # [0. 1. 0.]
print(np.cos(angle))  # [1. 0. -1.]
print(np.tan(angle))  # [ 0.00000000e+00  1.63312394e+16  1.22464680e-16]

# Exponential and Logarithmic
print(np.exp(x))  # [ 2.71828183  7.3890561  20.08553692]
print(np.log(x))  # [0.         0.69314718 1.09861229]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [68]:
# Hyperbolic sine, cosine, and tangent
print(np.sinh(angle))  # [ 0.          1.17520119  1.17520119]
print(np.cosh(angle))  # [1.         1.54308063 1.54308063]
print(np.tanh(angle))  # [0.         0.91715234 0.0]


[ 0.          2.3012989  11.54873936]
[ 1.          2.50917848 11.59195328]
[0.         0.91715234 0.99627208]


In [70]:
# Sum, Mean, Min, Max
print(np.sum(x))  # 6
print(np.mean(x))  # 2.0
print(np.min(x))  # 1
print(np.max(x))  # 3


6
2.0
1
3


In [72]:
# Dot product
a = np.array([1, 2])
b = np.array([3, 4])
print(np.dot(a, b))  # 11

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.matmul(A, B))  # [[19 22] [43 50]]

# Inverse of a matrix
print(np.linalg.inv(A))  # [[-2.  1.] [1.5 -0.5]]


11
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [74]:
# Element-wise comparison
print(np.equal([1, 2, 3], [1, 2, 4]))  # [ True  True False]

# Check if all elements are true
print(np.all([True, False, True]))  # False

# Check if any element is true
print(np.any([True, False, False]))  # True


[ True  True False]
False
True


In [76]:
# Random float in [0, 1)
print(np.random.rand(3))  # Example: [0.12345678 0.23456789 0.3456789]

# Random integers between 0 and 10
print(np.random.randint(0, 10,5))  # Example: [1 3 7 0 9]

# Random choice from an array
print(np.random.choice([1, 2, 3, 4]))  # Example: 3


[0.30389997 0.14332624 0.33041417]
[7 8 3 6 6]
3


In [78]:
print(np.random.randint(0, 10))

9


In [80]:
print(np.random.randint(0, 20))

16


In [82]:
#import statistics
import statistics
data = [1, 2, 3, 4, 5]
print(statistics.mean(data))  # Output: 3


3


In [87]:
import statistics

# Sample data
data = [1, 2, 3, 4, 5]

# Mean
print(f"Mean: {statistics.mean(data)}")

# Median
print(f"Median: {statistics.median(data)}")

# Mode
data_mode = [1, 2, 2, 3, 3, 3, 4]
print(f"Mode: {statistics.mode(data_mode)}")

# Standard Deviation
print(f"Standard Deviation: {statistics.stdev(data)}")

# Variance
print(f"Variance: {statistics.variance(data)}")

# Median Low and High
print(f"Median Low: {statistics.median_low([1, 2, 3, 4])}")
print(f"Median High: {statistics.median_high([1, 2, 3, 4])}")

# fmean (floating point mean)
print(f"fmean: {statistics.fmean(data)}")

# Geometric Mean
print(f"Geometric Mean: {statistics.geometric_mean(data)}")

# Harmonic Mean
print(f"Harmonic Mean: {statistics.harmonic_mean(data)}")

# Population Standard Deviation and Variance
print(f"Population Standard Deviation: {statistics.pstdev(data)}")
print(f"Population Variance: {statistics.pvariance(data)}")


Mean: 3
Median: 3
Mode: 3
Standard Deviation: 1.5811388300841898
Variance: 2.5
Median Low: 2
Median High: 3
fmean: 3.0
Geometric Mean: 2.6051710846973517
Harmonic Mean: 2.18978102189781
Population Standard Deviation: 1.4142135623730951
Population Variance: 2


In [89]:
data = [1, 2, 3, 4]
print(statistics.median_high(data))  # Output: 3


3
